/-
  Fee split: a model of `maya_fee_market::split` (crates/fee-market/src/split.rs)
  and the property the brief asks Lean to prove: the split sums to 100%.

  This is a hand-written model, not an Aeneas extraction: Aeneas/Charon are not
  wired into this tree (formal/README.md). `vectors` below is evaluated by Lean
  and written to formal/lean/vectors/fee_split.txt, and
  crates/fee-market/tests/lean_differential.rs checks the Rust function against
  every line — which is what ties this model to the code it describes.
-/

namespace Maya2C.FeeSplit

/-- Basis points in 100%. -/
def BPS : Nat := 10000

/-- `(burned, treasury, tip)` for a base fee, a tip, and a treasury share. -/
def split (base tip bps : Nat) : Nat × Nat × Nat :=
  let share := min bps BPS
  let treasury := base * share / BPS
  (base - treasury, treasury, tip)

theorem treasury_le_base (base bps : Nat) : base * min bps BPS / BPS ≤ base := by
  apply Nat.div_le_of_le_mul
  have h : min bps BPS ≤ BPS := Nat.min_le_right bps BPS
  calc base * min bps BPS ≤ base * BPS := Nat.mul_le_mul_left base h
    _ = BPS * base := Nat.mul_comm base BPS

/-- The split sums to exactly what was paid: nothing created, nothing lost. -/
theorem split_sums (base tip bps : Nat) :
    (split base tip bps).1 + (split base tip bps).2.1 + (split base tip bps).2.2 = base + tip := by
  have h := treasury_le_base base bps
  simp only [split]
  omega

/-- The treasury never receives more than its share allows, even for a bps
    above 100% (the Rust clamps with `min`, and so does the model). -/
theorem treasury_bounded (base tip bps : Nat) : (split base tip bps).2.1 ≤ base :=
  treasury_le_base base bps

/-- Differential vectors: a fixed grid of inputs. -/
def vectors : List (Nat × Nat × Nat × Nat × Nat × Nat) :=
  let bases := [0, 1, 7, 999, 10000, 123456789, 18446744073709551615]
  let bpss := [0, 1, 2000, 5000, 9999, 10000, 20000]
  bases.flatMap fun b => bpss.map fun s =>
    let (burned, treasury, tip) := split b 3 s
    (b, 3, s, burned, treasury, tip)

end Maya2C.FeeSplit

/-- `lean --run Maya2C/FeeSplit.lean > vectors/fee_split.txt` -/
def main : IO Unit := do
  IO.println "# base tip bps burned treasury tip  (generated by formal/lean/Maya2C/FeeSplit.lean)"
  for (b, t, s, burned, treasury, tip) in Maya2C.FeeSplit.vectors do
    IO.println s!"{b} {t} {s} {burned} {treasury} {tip}"
