//! The production node against `spec/tests/` (Master Prompt 15 §2).
//!
//! The vectors are generated by `crates/spec-ref`, which shares no code with
//! this crate. Every case is replayed here through the real entry points —
//! `Transaction::from_bytes`, real hybrid signatures, `StateDB::apply_block`,
//! `maya_fee_market` — and any disagreement fails with the case id.
//!
//! `spec/tests/keys.json` is the one file this side produces: the hybrid public
//! keys the node derives from four fixed seeds. The reference recomputes each
//! address from its key, so a divergence in address derivation shows up on
//! both sides. Regenerate with `MAYA_SPEC_BLESS=1`; otherwise it is checked.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::collections::BTreeMap;
use std::path::PathBuf;

use custom_l1_node::core::{Block, BlockHeader, Transaction, TxOutput};
use custom_l1_node::crypto::hybrid::{HybridSigningKey, signing_key_from_seed};
use custom_l1_node::crypto::pow::target_from_leading_zero_bits;
use custom_l1_node::error::NodeError;
use custom_l1_node::state::{Account, Address, BlockContext, StateDB};
use serde_json::{Value, json};

const KEYS: u8 = 4;

fn spec(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../spec/tests")
        .join(name)
}

fn load(name: &str) -> Value {
    serde_json::from_str(&std::fs::read_to_string(spec(name)).expect(name)).unwrap()
}

/// Vectors carry every u64 as a decimal string (see spec-vectors).
fn num(v: &Value) -> u64 {
    v.as_str()
        .expect("u64 fields are decimal strings")
        .parse()
        .expect("decimal u64")
}

fn unhex(s: &str) -> Vec<u8> {
    hex::decode(s).unwrap()
}

/// `k0..k3` from seeds `[1; 32] .. [4; 32]`.
fn node_keys() -> BTreeMap<String, HybridSigningKey> {
    (0..KEYS)
        .map(|i| {
            (
                format!("k{i}"),
                signing_key_from_seed(&[i + 1; 32]).unwrap(),
            )
        })
        .collect()
}

#[test]
fn key_table_matches_the_node() {
    let keys: Vec<Value> = node_keys()
        .iter()
        .enumerate()
        .map(|(i, (name, key))| {
            let mut pk = Vec::new();
            key.public_key().encode_into(&mut pk);
            json!({"name": name, "seed": hex::encode([u8::try_from(i).unwrap() + 1; 32]), "public_key": hex::encode(pk), "address": hex::encode(key.address())})
        })
        .collect();
    let doc = json!({"format": 1, "note": "hybrid ML-DSA-65 + SLH-DSA-SHA2-128s keys from custom_l1_node::crypto::hybrid::signing_key_from_seed; produced by crates/node/tests/conformance.rs", "keys": keys});
    let text = serde_json::to_string_pretty(&doc).unwrap() + "\n";
    if std::env::var("MAYA_SPEC_BLESS").is_ok() {
        std::fs::write(spec("keys.json"), &text).unwrap();
    }
    assert_eq!(
        std::fs::read_to_string(spec("keys.json")).unwrap(),
        text,
        "keys.json is stale: MAYA_SPEC_BLESS=1"
    );
}

fn address(keys: &BTreeMap<String, HybridSigningKey>, name: &str) -> Address {
    keys.get(name).map_or_else(
        || unhex(name).try_into().unwrap(),
        HybridSigningKey::address,
    )
}

fn signed(keys: &BTreeMap<String, HybridSigningKey>, t: &Value) -> Transaction {
    let outputs = t["outputs"]
        .as_array()
        .unwrap()
        .iter()
        .map(|o| TxOutput {
            amount: num(&o["amount"]),
            recipient: address(keys, o["to"].as_str().unwrap()),
        })
        .collect();
    let mut tx = Transaction::new(vec![], outputs, num(&t["nonce"]));
    tx.sign(&keys[t["from"].as_str().unwrap()]).unwrap();
    if t["signature"] == "invalid" {
        // One bit inside the SLH-DSA half, which ends a v5 frame.
        let mut bytes = tx.to_bytes();
        let at = bytes.len() - 100;
        bytes[at] ^= 1;
        tx = Transaction::from_bytes(&bytes).unwrap();
    }
    tx
}

fn kind(e: &NodeError) -> &'static str {
    match e {
        NodeError::InvalidNonce { .. } => "InvalidNonce",
        NodeError::InsufficientBalance { .. } => "InsufficientBalance",
        NodeError::BalanceOverflow => "BalanceOverflow",
        NodeError::MissingSignature
        | NodeError::SignatureVerification
        | NodeError::HashSignatureVerification
        | NodeError::MalformedPublicKey => "BadSignature",
        _ => "Other",
    }
}

fn block_of(transactions: Vec<Transaction>) -> Block {
    let header = BlockHeader {
        prev_hash: [0; 32],
        state_root: [0; 32],
        timestamp: 1_756_252_800,
        nonce: 0,
        difficulty_target: target_from_leading_zero_bits(0),
        tx_root: [0; 32],
    };
    Block::new(header, transactions)
}

fn run_stf_case(keys: &BTreeMap<String, HybridSigningKey>, case: &Value) {
    let id = case["id"].as_str().unwrap();
    let dir = tempfile::TempDir::new().unwrap();
    let db = StateDB::open(dir.path()).unwrap();
    for a in case["pre"].as_array().unwrap() {
        let acc = Account {
            balance: num(&a["balance"]),
            nonce: num(&a["nonce"]),
        };
        db.put_account(&address(keys, a["account"].as_str().unwrap()), &acc)
            .unwrap();
    }
    assert_eq!(
        hex::encode(db.state_root().unwrap()),
        case["pre_root"].as_str().unwrap(),
        "{id}: pre_root"
    );
    let txs = case["block"]
        .as_array()
        .unwrap()
        .iter()
        .map(|t| signed(keys, t))
        .collect();
    let expect = &case["expect"];
    match db.apply_block(&block_of(txs), BlockContext::GENESIS) {
        Ok(root) => {
            assert_eq!(
                expect["result"], "ok",
                "{id}: node accepted a block the reference rejects ({})",
                expect["error"]
            );
            assert_eq!(
                hex::encode(root),
                expect["post_root"].as_str().unwrap(),
                "{id}: post_root"
            );
            for a in expect["post"].as_array().unwrap() {
                let acc = db
                    .get_account(&unhex(a["address"].as_str().unwrap()).try_into().unwrap())
                    .unwrap();
                assert_eq!(
                    (acc.balance, acc.nonce),
                    (num(&a["balance"]), num(&a["nonce"])),
                    "{id}: post account"
                );
            }
        }
        Err(e) => {
            assert_eq!(
                expect["result"], "error",
                "{id}: node rejected a valid block: {e}"
            );
            assert_eq!(
                kind(&e),
                expect["error"].as_str().unwrap(),
                "{id}: wrong error kind ({e})"
            );
            assert_eq!(
                hex::encode(db.state_root().unwrap()),
                case["pre_root"].as_str().unwrap(),
                "{id}: a refused block changed state"
            );
        }
    }
}

#[test]
fn state_transition_vectors() {
    let keys = node_keys();
    let doc = load("state_transitions.json");
    let cases = doc["cases"].as_array().unwrap();
    for case in cases {
        run_stf_case(&keys, case);
    }
    println!(
        "{} state-transition vectors agree with the reference",
        cases.len()
    );
}

#[test]
fn encoding_vectors() {
    let doc = load("encoding.json");
    for case in doc["cases"].as_array().unwrap() {
        let id = case["id"].as_str().unwrap();
        let bytes = unhex(case["bytes"].as_str().unwrap());
        match (
            Transaction::from_bytes(&bytes),
            case["expect"]["result"].as_str().unwrap(),
        ) {
            (Ok(tx), "ok") => {
                assert_eq!(tx.to_bytes(), bytes, "{id}: not canonical");
                assert_eq!(
                    hex::encode(tx.txid()),
                    case["expect"]["txid"].as_str().unwrap(),
                    "{id}: txid"
                );
                assert_eq!(
                    hex::encode(tx.sender()),
                    case["expect"]["sender"].as_str().unwrap(),
                    "{id}: sender"
                );
                assert_eq!(tx.nonce, num(&case["expect"]["nonce"]), "{id}: nonce");
            }
            (Err(NodeError::Decode(_)), "error") => {}
            (other, want) => panic!("{id}: expected {want}, node gave {other:?}"),
        }
    }
}

#[test]
fn fee_vectors() {
    let doc = load("fees.json");
    for case in doc["cases"].as_array().unwrap() {
        let id = case["id"].as_str().unwrap();
        let n = |k: &str| num(&case[k]);
        match case["fn"].as_str().unwrap() {
            "split" => {
                let s = maya_fee_market::split(n("base_fee_paid"), 0, n("treasury_bps"));
                assert_eq!(
                    (s.burned, s.treasury),
                    (
                        num(&case["expect"]["burned"]),
                        num(&case["expect"]["treasury"])
                    ),
                    "{id}"
                );
            }
            "next_base_fee" => {
                let got = maya_fee_market::next_base_fee(
                    n("parent_base_fee"),
                    n("parent_size"),
                    n("target"),
                    n("denominator"),
                    n("floor"),
                );
                assert_eq!(got, num(&case["expect"]), "{id}");
            }
            "admit" => {
                let c = maya_fee_market::FeeConfig::TESTING;
                assert_eq!(
                    n("base_fee"),
                    c.initial_base_fee,
                    "{id}: vectors assume the testing config's initial base fee"
                );
                let tx = maya_fee_market::TxFee {
                    size_bytes: n("size_bytes"),
                    max_fee: n("max_fee"),
                    max_tip: 0,
                };
                let got = maya_fee_market::apply_block_fees(
                    &c,
                    1,
                    None,
                    &[tx],
                    &[maya_fee_market::FeeClaim {
                        beneficiary: [7; 32],
                    }],
                );
                match (got, case["expect"]["result"].as_str().unwrap()) {
                    (Ok(_), "ok")
                    | (Err(maya_fee_market::FeeError::Underpriced { .. }), "error") => {}
                    (other, want) => panic!("{id}: expected {want}, fee market gave {other:?}"),
                }
            }
            other => panic!("{id}: unknown fn {other}"),
        }
    }
}

fn header_of(h: &Value) -> BlockHeader {
    let arr = |k: &str| -> [u8; 32] { unhex(h[k].as_str().unwrap()).try_into().unwrap() };
    BlockHeader {
        prev_hash: arr("prev_hash"),
        state_root: arr("state_root"),
        timestamp: num(&h["timestamp"]),
        nonce: num(&h["nonce"]),
        difficulty_target: arr("difficulty_target"),
        tx_root: arr("tx_root"),
    }
}

#[test]
fn header_vectors() {
    let doc = load("headers.json");
    for case in doc["cases"].as_array().unwrap() {
        let id = case["id"].as_str().unwrap();
        let header = header_of(&case["header"]);
        let expect = &case["expect"];
        let Some(txs) = case["transactions"].as_array() else {
            assert_eq!(
                hex::encode(header.serialize()),
                expect["bytes"].as_str().unwrap(),
                "{id}: bytes"
            );
            assert_eq!(
                hex::encode(header.id()),
                expect["id"].as_str().unwrap(),
                "{id}: id"
            );
            continue;
        };
        // Built directly, not through Block::new, which would overwrite tx_root.
        let transactions = txs
            .iter()
            .map(|t| Transaction::from_bytes(&unhex(t.as_str().unwrap())).unwrap())
            .collect();
        let block = Block {
            header,
            transactions,
        };
        match (block.check_tx_root(), expect["result"].as_str().unwrap()) {
            (Ok(()), "ok") => assert_eq!(
                hex::encode(block.tx_root()),
                expect["tx_root"].as_str().unwrap(),
                "{id}: tx_root"
            ),
            (Err(_), "error") => {}
            (other, want) => panic!("{id}: expected {want}, node gave {other:?}"),
        }
    }
}
