#!/bin/bash
# Generates a staging net: N validator keys, one genesis, and a compose file
# that runs each validator in its own container with its own IP and WAN link.
#
#   infra/stagenet/gen.sh <bin-dir> <out-dir> [validators]
#
# <bin-dir> holds Linux builds of maya2c-node and l1-wallet. Run inside WSL
# (or any Linux host with Docker), then `docker compose -f <out>/compose.yml up -d`.
#
# Every container shares one physical machine. This exercises networking,
# latency and failure handling; it is NOT gate 4 (separate machines, separate
# operators), and nothing produced here may be described as independent.
set -euo pipefail

BIN=${1:?bin dir}
OUT=${2:?out dir}
N=${3:-7}
SUBNET_PREFIX=172.30.0
FIRST_HOST=11
BOND=1000000000000
BALANCE=1000000000000000000
EPOCH_BLOCKS=60
# Per-validator links, cycled: different "regions" so no two neighbours share
# a profile. Latency is one-way at each end, so a pair sees the sum.
LINKS=(
    "delay 15ms 3ms"
    "delay 45ms 8ms loss 0.2%"
    "delay 80ms 15ms loss 0.5%"
    "delay 30ms 5ms"
    "delay 120ms 20ms loss 1%"
    "delay 60ms 10ms loss 0.3%"
    "delay 25ms 4ms"
)

rm -rf "$OUT"
mkdir -p "$OUT"
cp "$(dirname "$0")/Dockerfile" "$(dirname "$0")/entrypoint.sh" "$BIN/maya2c-node" "$OUT/"
chmod +x "$OUT/entrypoint.sh"

keys=()
for i in $(seq 0 $((N - 1))); do
    mkdir -p "$OUT/v$i"
    keys+=("$("$BIN/maya2c-node" --generate-validator-key "$OUT/v$i/validator.key" | tr -d '[:space:]')")
done

# A throwaway password: this keystore only ever holds staging coins.
wallet_password=$(head -c 18 /dev/urandom | base64)
printf '%s' "$wallet_password" > "$OUT/wallet.password"
chmod 600 "$OUT/wallet.password"
address=$(L1_WALLET_PASSWORD="$wallet_password" "$BIN/l1-wallet" --keystore "$OUT/wallet.key" generate \
    | sed -n 's/.*address[^0-9a-zA-Z]*\([0-9a-zA-Z]\{20,\}\).*/\1/p' | head -n 1)
[ -n "$address" ] || { echo "l1-wallet printed no address" >&2; exit 1; }

validators_json=$(printf '"%s",' "${keys[@]}")
bonds_json=$(for _ in "${keys[@]}"; do printf '{"operator":"%s","bond":%s},' "$address" "$BOND"; done)
cat > "$OUT/genesis.json" <<JSON
{"chain_id":"maya2c-stagenet","timestamp":$(date +%s),"difficulty_bits":0,"pow_limit_bits":0,
 "allocations":[{"address":"$address","balance":$BALANCE}],
 "bft":{"validators":[${validators_json%,}],"anchor_timeout_ms":1000,"batch_size":500,
  "staking":{"epoch_blocks":$EPOCH_BLOCKS,"bonds":[${bonds_json%,}],"stake_weighted":true}}}
JSON

{
    echo "# Generated by infra/stagenet/gen.sh. One physical PC; see README.md."
    echo "name: maya2c-stagenet"
    echo "networks:"
    echo "  stage:"
    echo "    ipam:"
    echo "      config: [{ subnet: \"$SUBNET_PREFIX.0/24\" }]"
    echo "services:"
    for i in $(seq 0 $((N - 1))); do
        ip="$SUBNET_PREFIX.$((FIRST_HOST + i))"
        echo "  v$i:"
        echo "    build: ."
        echo "    image: maya2c-stagenet:local"
        echo "    hostname: v$i"
        echo "    cap_add: [NET_ADMIN]"
        echo "    environment: { NETEM: \"${LINKS[$((i % ${#LINKS[@]}))]}\" }"
        echo "    networks: { stage: { ipv4_address: \"$ip\" } }"
        echo "    mem_limit: 1g"
        echo "    cpus: 2"
        echo "    restart: \"no\""
        echo "    volumes:"
        echo "      - ./genesis.json:/genesis.json:ro"
        echo "      - ./v$i:/data"
        echo "    command:"
        echo "      - --genesis"
        echo "      - /genesis.json"
        echo "      - --data-dir"
        echo "      - /data"
        echo "      - --validator-key"
        echo "      - /data/validator.key"
        echo "      - --rpc-addr"
        echo "      - 0.0.0.0:8545"
        echo "      - --p2p-port"
        echo "      - \"30333\""
        echo "      - --snapshot-interval"
        echo "      - \"20\""
        echo "      - --snapshot-depth"
        echo "      - \"20\""
        for p in $(seq 0 $((N - 1))); do
            [ "$p" -eq "$i" ] && continue
            echo "      - --bootnode"
            echo "      - /ip4/$SUBNET_PREFIX.$((FIRST_HOST + p))/tcp/30333"
        done
    done
} > "$OUT/compose.yml"

echo "stagenet: $N validators in $OUT (rpc: http://$SUBNET_PREFIX.$FIRST_HOST..$((FIRST_HOST + N - 1)):8545)"
