#!/usr/bin/env python3
"""Turns criterion's JSON into CSV and Markdown comparison tables.

    cargo bench --bench algo_comparison
    python scripts/bench_report.py

Reads ``target/criterion/**/new/estimates.json`` — criterion's own output, so
the numbers in the report are the numbers criterion measured and not a
transcription of them.

Energy
------

Every joule figure is ``measured seconds x ASSUMED_PACKAGE_WATTS``, and the
assumption is printed in the report next to the results rather than in a
footnote. RAPL is not readable without a driver on Windows, so package power
is an input here, not a reading.

There is deliberately no energy-per-transaction column. That quantity needs
network hashrate and a hardware mix, neither observable, and Maya2C has no live
network — its hashrate is zero and the quotient undefined.
"""

from __future__ import annotations

import csv
import json
from dataclasses import dataclass
from pathlib import Path

CRITERION = Path("target/criterion")
CSV_OUT = Path("docs/benchmarks/algo_comparison.csv")
MD_OUT = Path("docs/benchmarks/algo_comparison.md")

# Assumed package power for the joules-per-operation model. The single input a
# reader should challenge first; kept identical to `crates/node/benches/algo_comparison.rs`.
ASSUMED_PACKAGE_WATTS = 45.0


@dataclass(frozen=True)
class Measurement:
    group: str
    name: str
    nanos: float

    @property
    def seconds(self) -> float:
        return self.nanos / 1e9

    @property
    def joules(self) -> float:
        return self.seconds * ASSUMED_PACKAGE_WATTS

    @property
    def per_second(self) -> float:
        return 1.0 / self.seconds if self.seconds > 0 else float("inf")


def collect() -> list[Measurement]:
    """Reads every completed measurement criterion left behind."""
    found: list[Measurement] = []
    if not CRITERION.is_dir():
        return found

    for estimates in sorted(CRITERION.glob("*/*/new/estimates.json")):
        # .../criterion/<group>/<bench>/new/estimates.json
        bench_dir = estimates.parent.parent
        group = bench_dir.parent.name
        name = bench_dir.name

        with estimates.open(encoding="utf-8") as handle:
            data = json.load(handle)

        # The median rather than the mean. Criterion reports both; a benchmark
        # on a laptop picks up scheduler noise as a long tail, and the median is
        # the statistic that does not move when one sample lands during a
        # background compile.
        try:
            nanos = float(data["median"]["point_estimate"])
        except (KeyError, TypeError, ValueError):
            continue

        found.append(Measurement(group=group, name=name, nanos=nanos))

    return found


def humanise(seconds: float) -> str:
    """A duration in the unit a reader can hold in their head."""
    if seconds >= 1e-3:
        return f"{seconds * 1e3:.3f} ms"
    if seconds >= 1e-6:
        return f"{seconds * 1e6:.3f} us"
    return f"{seconds * 1e9:.1f} ns"


def write_csv(rows: list[Measurement]) -> None:
    CSV_OUT.parent.mkdir(parents=True, exist_ok=True)
    with CSV_OUT.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(
            [
                "group",
                "algorithm",
                "median_ns",
                "ops_per_second",
                "modelled_joules_per_op",
                "assumed_watts",
            ]
        )
        for row in rows:
            writer.writerow(
                [
                    row.group,
                    row.name,
                    f"{row.nanos:.1f}",
                    f"{row.per_second:.2f}",
                    f"{row.joules:.9f}",
                    ASSUMED_PACKAGE_WATTS,
                ]
            )


def write_markdown(rows: list[Measurement]) -> None:
    MD_OUT.parent.mkdir(parents=True, exist_ok=True)
    groups: dict[str, list[Measurement]] = {}
    for row in rows:
        groups.setdefault(row.group, []).append(row)

    lines: list[str] = [
        "# Comparative benchmark results",
        "",
        "Generated by `scripts/bench_report.py` from criterion's own JSON.",
        "Re-run with `cargo bench --bench algo_comparison`.",
        "",
        "## Read this before the numbers",
        "",
        "**Two categories, not one.** SHA-256 is a proof-of-work hash; Ed25519 and",
        "ML-DSA+SLH-DSA are signature schemes. They are tabulated separately and no",
        "figure is compared across them. Note also that **Bitcoin does not use",
        "Ed25519** — its signatures are ECDSA over secp256k1, and Schnorr since",
        "Taproot. Ed25519 is here as the fast classical baseline, not as Bitcoin's.",
        "",
        "**Energy is modelled, not measured.** Every joule figure below is",
        f"`measured seconds x {ASSUMED_PACKAGE_WATTS} W`, and that wattage is an",
        "assumption. RAPL is not readable without a driver on this platform, so",
        "package power is an input, not a reading. Challenge it first.",
        "",
        "**There is no energy-per-transaction figure.** That needs network hashrate",
        "and a hardware mix, neither observable — published Bitcoin estimates carry",
        "roughly a factor-of-two spread for this reason. Maya2C has no live network,",
        "so its hashrate is zero and the quotient is undefined.",
        "",
        "**No `finalized` metric either.** Maya2C and Bitcoin have probabilistic",
        "finality: there is no finalisation event, only confirmations accumulating.",
        "",
        "**kHeavyHash (Kaspa) is absent.** No `kheavyhash` crate exists; Kaspa's own",
        "`kaspa-pow` has the right implementation and an official test vector but",
        "depends transitively on `workflow-core 0.18`, which does not compile on this",
        "toolchain. Hand-implementing it was refused: with no official vectors, a",
        "wrong implementation would publish a number misrepresenting Kaspa and",
        "nothing here would catch it.",
        "",
        "**Single machine.** These are one host's numbers. Nothing here supports a",
        "cross-machine claim.",
        "",
    ]

    for group in sorted(groups):
        lines.append(f"## {group}")
        lines.append("")
        lines.append("| algorithm | median | ops/s | modelled J/op |")
        lines.append("|---|---:|---:|---:|")
        for row in sorted(groups[group], key=lambda r: r.nanos):
            lines.append(
                f"| {row.name} | {humanise(row.seconds)} "
                f"| {row.per_second:,.1f} | {row.joules:.3e} |"
            )
        lines.append("")

        # A ratio is the only cross-row arithmetic that is meaningful, and only
        # within a group.
        ordered = sorted(groups[group], key=lambda r: r.nanos)
        if len(ordered) >= 2:
            fastest, slowest = ordered[0], ordered[-1]
            ratio = slowest.nanos / fastest.nanos if fastest.nanos else float("inf")
            lines.append(
                f"`{slowest.name}` is **{ratio:,.0f}x** the cost of "
                f"`{fastest.name}` in this group."
            )
            lines.append("")

    MD_OUT.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    rows = collect()
    if not rows:
        print("no criterion output found; run `cargo bench --bench algo_comparison` first")
        return 1

    write_csv(rows)
    write_markdown(rows)
    print(f"{len(rows)} measurements -> {CSV_OUT} and {MD_OUT}")
    for row in sorted(rows, key=lambda r: (r.group, r.nanos)):
        print(f"  {row.group:<24} {row.name:<34} {humanise(row.seconds):>12}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
