#!/usr/bin/env bash
#
# configure_environment.sh — collect deployment credentials (Master Prompt 10 §6).
#
# YOU run this, at a terminal. Nobody should ever paste a secret into a chat,
# an issue, or a commit — including into a conversation with an AI assistant.
#
# What it does:
#   1. Prompts for each credential with hidden input (read -s). Nothing is
#      echoed, logged, or placed on a command line (where `ps` would show it).
#   2. Validates each token against its provider's API with a read-only call.
#   3. Encrypts everything with `age` to .env.production.age (git-ignored) and
#      writes the age identity to ~/.config/maya2c/age.key (mode 0600). The
#      plaintext never touches disk.
#   4. Writes the NON-secret outputs: infra/terraform/terraform.tfvars
#      (regions, domain, node counts) and infra/ansible/inventory/production.ini.
#   5. Prints a pre-flight checklist.
#
# Flags: --no-validate (offline; skips the provider calls)
#        --non-interactive (read secrets from stdin, one per line, in prompt
#        order — for a secrets manager piping into it, never for a human)

set -euo pipefail
cd "$(dirname "$0")/.."

VALIDATE=1
INTERACTIVE=1
for a in "$@"; do
    case "$a" in
        --no-validate) VALIDATE=0 ;;
        --non-interactive) INTERACTIVE=0 ;;
        -h|--help) sed -n '2,22p' "$0"; exit 0 ;;
        *) echo "unknown flag: $a" >&2; exit 2 ;;
    esac
done

command -v age >/dev/null || { echo "age is required (https://age-encryption.org)" >&2; exit 1; }
command -v curl >/dev/null || { echo "curl is required" >&2; exit 1; }

umask 077
declare -A SECRET
declare -A PLAIN

ask_secret() { # ask_secret KEY "prompt"
    local v=""
    if ((INTERACTIVE)); then
        read -r -s -p "$2: " v; echo
    else
        read -r v
    fi
    SECRET[$1]="$v"
}
ask_plain() { # ask_plain KEY "prompt" default
    local v=""
    if ((INTERACTIVE)); then
        read -r -p "$2 [$3]: " v
    else
        read -r v
    fi
    PLAIN[$1]="${v:-$3}"
}

echo "Maya2C deployment credentials. Input is hidden; press Enter to skip a provider."
ask_secret HCLOUD_TOKEN "Hetzner Cloud API token"
ask_secret VULTR_API_KEY "Vultr API key"
ask_secret AWS_ACCESS_KEY_ID "AWS access key id"
ask_secret AWS_SECRET_ACCESS_KEY "AWS secret access key"
ask_secret CLOUDFLARE_API_TOKEN "Cloudflare API token"
ask_plain CLOUDFLARE_ZONE_ID "Cloudflare zone id" ""
ask_plain DOMAIN "Public domain" "example.invalid"
ask_plain LE_EMAIL "Let's Encrypt contact email" ""
ask_plain SSH_KEY_PATH "SSH public key path" "$HOME/.ssh/id_ed25519.pub"
ask_secret GENESIS_OWNER_SIGNATURE "Genesis owner signature (hex)"

status=()
check() { # check NAME <curl args...>: a read-only call; 2xx = valid
    local name=$1; shift
    local code
    code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 15 "$@" || echo 000)
    if [[ "$code" =~ ^2 ]]; then status+=("  [ok]   $name"); else status+=("  [FAIL] $name (HTTP $code)"); fi
}
if ((VALIDATE)); then
    # Headers go through curl's config on stdin (-K -) so tokens never appear
    # in the process list.
    if [[ -n "${SECRET[HCLOUD_TOKEN]}" ]]; then
        check "Hetzner token" -K - https://api.hetzner.cloud/v1/locations \
            <<<"header = \"Authorization: Bearer ${SECRET[HCLOUD_TOKEN]}\""
    fi
    if [[ -n "${SECRET[VULTR_API_KEY]}" ]]; then
        check "Vultr key" -K - https://api.vultr.com/v2/account \
            <<<"header = \"Authorization: Bearer ${SECRET[VULTR_API_KEY]}\""
    fi
    if [[ -n "${SECRET[CLOUDFLARE_API_TOKEN]}" ]]; then
        check "Cloudflare token" -K - https://api.cloudflare.com/client/v4/user/tokens/verify \
            <<<"header = \"Authorization: Bearer ${SECRET[CLOUDFLARE_API_TOKEN]}\""
    fi
    if [[ -n "${SECRET[AWS_ACCESS_KEY_ID]}" ]]; then
        if command -v aws >/dev/null; then
            if AWS_ACCESS_KEY_ID="${SECRET[AWS_ACCESS_KEY_ID]}" AWS_SECRET_ACCESS_KEY="${SECRET[AWS_SECRET_ACCESS_KEY]}" \
                aws sts get-caller-identity >/dev/null 2>&1; then status+=("  [ok]   AWS keys"); else status+=("  [FAIL] AWS keys"); fi
        else
            status+=("  [skip] AWS keys (aws CLI not installed)")
        fi
    fi
else
    status+=("  [skip] provider validation (--no-validate)")
fi

# Encrypt: plaintext goes from memory to age's stdin, never to a file.
KEY_DIR="$HOME/.config/maya2c"
mkdir -p "$KEY_DIR"
[[ -f "$KEY_DIR/age.key" ]] || age-keygen -o "$KEY_DIR/age.key" 2>/dev/null
RECIPIENT=$(grep -o 'age1[0-9a-z]*' "$KEY_DIR/age.key" | head -1)
{
    for k in "${!SECRET[@]}"; do
        if [[ -n "${SECRET[$k]}" ]]; then printf '%s=%s\n' "$k" "${SECRET[$k]}"; fi
    done
} | age -r "$RECIPIENT" -o .env.production.age
for k in "${!SECRET[@]}"; do SECRET[$k]=""; done

# Non-secret outputs.
cat > infra/terraform/terraform.tfvars <<EOF
# Generated by scripts/configure_environment.sh. No secrets: provider tokens
# are read from .env.production.age at apply time.
domain           = "${PLAIN[DOMAIN]}"
cloudflare_zone  = "${PLAIN[CLOUDFLARE_ZONE_ID]}"
regions          = ["na", "eu", "asia"]
validators       = 12
ssh_public_key   = "${PLAIN[SSH_KEY_PATH]}"
EOF
mkdir -p infra/ansible/inventory
cat > infra/ansible/inventory/production.ini <<EOF
# Generated by scripts/configure_environment.sh; hosts are filled from
# terraform output after an APPROVED apply.
[validators]
[rpc]
[all:vars]
letsencrypt_email=${PLAIN[LE_EMAIL]}
public_domain=${PLAIN[DOMAIN]}
EOF

echo
echo "Pre-flight checklist"
printf '%s\n' "${status[@]}"
echo "  [ok]   secrets encrypted to .env.production.age (identity: $KEY_DIR/age.key)"
echo "  [todo] DNS zone ${PLAIN[CLOUDFLARE_ZONE_ID]:-<unset>} delegates ${PLAIN[DOMAIN]}"
echo "  [todo] ports open on the provider firewall: 30333/tcp (p2p), 443/tcp (RPC via gateway)"
echo "  [todo] review infra/terraform/terraform.tfvars, then: ./deploy-production.sh (dry run)"
