#!/usr/bin/env bash
#
# pre_ignition_audit.sh — the readiness manifest (Master Prompt 10 §7).
#
# Runs every check this machine can run and writes
# reports/readiness-manifest.md with the raw evidence of each and a list of
# KNOWN RISKS. A check that cannot run here (no GPU, no TEE hardware, no Kani)
# is recorded as SKIPPED with the reason — never as passed.
#
# Usage: scripts/pre_ignition_audit.sh [--quick]
#   --quick   skip the full test suite (use the last recorded run)

set -uo pipefail
cd "$(dirname "$0")/.." || exit 1
OUT=reports/readiness-manifest.md
QUICK=0
[[ "${1:-}" == "--quick" ]] && QUICK=1
LOG=$(mktemp -d)

run() { # run <name> <cmd...>: records PASS/FAIL with the last lines of output
    local name=$1; shift
    if "$@" >"$LOG/$name.log" 2>&1; then
        printf '| %s | PASS | `%s` |\n' "$name" "$*"
    else
        printf '| %s | **FAIL** | `%s` |\n' "$name" "$*"
    fi
}
skip() { printf '| %s | SKIPPED | %s |\n' "$1" "$2"; }

{
    echo "# Readiness manifest"
    echo
    echo "Generated by \`scripts/pre_ignition_audit.sh\` at commit \`$(git rev-parse --short HEAD)\` on $(uname -srm)."
    echo "Raw logs were written to a temporary directory for this run; the table records the verdict and command."
    echo
    echo "| Check | Result | Command / reason |"
    echo "|---|---|---|"
    run build cargo build --workspace --profile ci
    if ((QUICK)); then
        skip tests "--quick: see reports/raw-test-baseline-2026-09-27.log"
    else
        run tests cargo test --workspace --profile ci --no-fail-fast
    fi
    run ledger cargo xtask coverage --quiet
    run readiness cargo xtask readiness --check
    run release-check cargo xtask release-check
    if command -v lean >/dev/null; then
        run lean bash -c 'cd formal/lean && lean Maya2C/FeeSplit.lean && lean Maya2C/Supply.lean'
    else
        skip lean "lean not installed"
    fi
    if python3 -c 'import z3' 2>/dev/null; then
        run z3 python3 formal/z3/fee_market.py
    else
        skip z3 "z3-solver not installed"
    fi
    if command -v cargo-kani >/dev/null; then
        run kani cargo kani -p maya-ledger-math
    else
        skip kani "cargo-kani not installed"
    fi
    if command -v cargo-deny >/dev/null; then
        run deny cargo deny check
    else
        skip deny "cargo-deny not installed"
    fi
    if command -v cargo-audit >/dev/null; then
        run audit cargo audit
    else
        skip audit "cargo-audit not installed"
    fi
    skip tee-quotes "no SGX/SEV-SNP/TDX hardware; quote verification is not built (reports/05-vm.md)"
    if command -v nvidia-smi >/dev/null || ls /dev/dri/renderD* >/dev/null 2>&1; then
        run gpu cargo test -p maya-wgpu-miner --features gpu -- --test-threads=1
    else
        skip gpu "no GPU adapter"
    fi
    skip ebpf "XDP load needs root + veth (scripts/xdp_netns.sh); CI job ebpf-net.yml"
    echo
    echo "## KNOWN RISKS"
    echo
    echo "1. The node's consensus is ArgonBlake PoW; DAG-BFT is an engine under the simulator (ADR-015). A production build refuses to start (ADR-016)."
    echo "2. Staking and slashing are not built; the fee market is dark (activation u64::MAX)."
    echo "3. The shielded pool's circuit has had no external audit (CIRCUIT_IS_AUDITED = false)."
    echo "4. HQC decapsulation is not constant-time (dudect |t| 47.5); HQC stays off by default (ADR-009)."
    echo "5. Threshold Raccoon's dealerless keygen is this project's own construction, not peer reviewed (ADR-014)."
    echo "6. No external security audit, no public testnet, no measured SLO."
    echo "7. Lean/Z3 proofs are over hand-written models; only the fee split is tied to the Rust by differential vectors."
} > "$OUT"
echo "wrote $OUT"
grep -c "| PASS |" "$OUT" | xargs echo "PASS:"
grep -c "FAIL" "$OUT" | xargs echo "FAIL lines:"
