"""Known-answer vectors for custody-mpc's Threshold Raccoon port, generated by
the scheme authors' own Python reference.

    PYTHONPATH=<dir with pycryptodome + mpmath> python scripts/traccoon_vectors.py

The reference is masksign/ec24-thrc (the Raccoon team's code for the
EUROCRYPT 2024 paper), fetched at a pinned commit. It runs a 3-of-5 session --
parties 0, 2 and 4 sign; 1 and 3 are offline -- with NIST's KAT DRBG as its
randomness, and this script records:

- every `random_bytes` draw (the key material the Rust API takes explicitly);
- every rounded-Gaussian sample, with the seed it was drawn from. The
  reference samples at 256-bit mpmath precision, which no f64 sampler can
  reproduce bit for bit, so the Rust test *feeds* these samples in and checks
  that its own seed derivation names the same seeds;
- a SHA3-256 digest of every intermediate and output, so the Rust must match
  the reference exactly at every step, not only at the end.

Outputs `crates/custody-mpc/tests/fixtures/traccoon_kat.json` (digests, draws,
seeds) and `traccoon_kat_samples.bin` (the samples, 6-byte little-endian
two's complement each, in draw order), and writes the reference's NTT twiddle
table to `crates/custody-mpc/src/threshold/ntt_table.rs`. The table is not an
implementation detail: the reference samples `A` directly in the NTT domain,
so `A`'s coefficients are defined *through* this NTT, and a port with any
other root ordering computes a different key.
"""
import subprocess
import contextlib
import hashlib
import io
import json
import os
import sys
import tempfile
import urllib.request

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
COMMIT = "8ef114a100e35feec69ca1121f168eef1dba0aca"
RAW = "https://raw.githubusercontent.com/masksign/ec24-thrc/" + COMMIT + "/thrc-py/"
FILES = ["thrc_core.py", "thrc_gauss.py", "polyr.py", "nist_kat_drbg.py", "thrc_api.py"]
T, N, ACT = 3, 5, [0, 2, 4]
SAMPLE_BYTES = 6

work = tempfile.mkdtemp(prefix="thrc-")
for name in FILES:
    with urllib.request.urlopen(RAW + name, timeout=30) as r:
        io.open(os.path.join(work, name), "wb").write(r.read())
sys.path.insert(0, work)

import thrc_core  # noqa: E402
from nist_kat_drbg import NIST_KAT_DRBG  # noqa: E402
import polyr  # noqa: E402
from polyr import RACC_Q  # noqa: E402

draws = []
samples = []
real_sample = thrc_core.sample_rounded


def recording_sample(sig2, seed, *args, **kwargs):
    values = real_sample(sig2, seed, *args, **kwargs)
    # A copy: the reference goes on to use these lists, and a recording that
    # aliased them would store whatever they had become by the end, not what
    # the sampler returned.
    samples.append({"sig2": repr(float(sig2)), "seed": seed.hex(), "values": list(values)})
    return values


thrc_core.sample_rounded = recording_sample
drbg = NIST_KAT_DRBG(bytes(range(48)))


def recording_random(n):
    out = drbg.random_bytes(n)
    draws.append(out.hex())
    return out


def coeffs(v):
    """Flatten a poly / vector of polys to canonical coefficients in [0, q)."""
    if isinstance(v, list) and v and isinstance(v[0], list):
        return [c for p in v for c in coeffs(p)]
    return [x % RACC_Q for x in v]


def digest(*parts):
    h = hashlib.sha3_256()
    for p in parts:
        if isinstance(p, (bytes, bytearray)):
            h.update(p)
        else:
            for c in coeffs(p):
                h.update(int(c).to_bytes(7, "little"))
    return h.hexdigest()


iut = thrc_core.ThRc_Core(kappa=128, random_bytes=recording_random)
mu = bytes(range(iut.mu_sz))
sid = bytes(range(100, 100 + iut.sid_sz))

with contextlib.redirect_stdout(io.StringIO()):
    vk, sk = iut.keygen(th_t=T, th_n=N)
    views, c1, c2, c3 = [None] * N, [None] * N, [None] * N, [None] * N
    for j in ACT:
        views[j], c1[j] = iut.sign_1(vk, sk[j], sid, ACT, mu)
    for j in ACT:
        c2[j] = iut.sign_2(views[j], c1)
    for j in ACT:
        c3[j] = iut.sign_3(views[j], c2)
    sig = iut.combine(vk, sid, mu, ACT, c1, c2, c3)
    ok = iut.verify(vk, mu, sig)
    # A tampered message must not verify under the same signature.
    bad = iut.verify(vk, bytes(32), sig)

assert sig is not None and ok and not bad
(A_seed, t) = vk
(c_hash, z, h) = sig

kat = {
    "reference": f"masksign/ec24-thrc@{COMMIT} thrc-py",
    "params": {"kappa": 128, "T": T, "N": N, "act": ACT},
    "mu": mu.hex(),
    "sid": sid.hex(),
    "random_draws": draws,
    "sample_seeds": [s["seed"] for s in samples],
    "sample_sig2": [s["sig2"] for s in samples],
    "a_seed": A_seed.hex(),
    "t": digest(t),
    "shares": {str(i): digest(sk[i][1]) for i in range(N)},
    "pair_seeds": {f"{i},{j}": sk[i][2][j][0].hex() for i in range(N) for j in range(N)},
    "cmt": {str(j): c1[j][0].hex() for j in ACT},
    "m": {str(j): digest(c1[j][1]) for j in ACT},
    "w": {str(j): digest(c2[j][0]) for j in ACT},
    "macs": {str(j): [m.hex() for m in c2[j][1]] for j in ACT},
    "z_share": {str(j): digest(c3[j]) for j in ACT},
    "sig_c": c_hash.hex(),
    "sig_z": digest(z),
    "sig_h": digest(h),
    "b2": repr(iut.b2),
}

fixtures = os.path.join(REPO, "crates/custody-mpc/tests/fixtures")
os.makedirs(fixtures, exist_ok=True)
json.dump(kat, io.open(os.path.join(fixtures, "traccoon_kat.json"), "w", encoding="utf-8"), indent=1)
lim = 1 << (8 * SAMPLE_BYTES - 1)
with io.open(os.path.join(fixtures, "traccoon_kat_samples.bin"), "wb") as out:
    for s in samples:
        for v in s["values"]:
            assert -lim <= v < lim
            out.write(int(v).to_bytes(SAMPLE_BYTES, "little", signed=True))
print(f"draws={len(draws)} sample_polys={len(samples)} verify={ok} c={c_hash.hex()[:16]}")

table = os.path.join(REPO, "crates/custody-mpc/src/threshold/ntt_table.rs")
NL = "\n"
body = ("," + NL).join("    " + str(w) for w in polyr.RACC_W)
header = [
    "//! The reference's NTT twiddle factors (`polyr.py`, `RACC_W`) and `n^-1 mod q`,",
    f"//! copied from masksign/ec24-thrc@{COMMIT} by `scripts/traccoon_vectors.py` --",
    "//! not retyped. The reference samples `A` in the NTT domain, so these define",
    "//! `A`'s coefficients: a different root ordering is a different key.",
    "",
    "// Upstream's decimal literals, digit for digit, so they compare by eye.",
    "#![allow(clippy::unreadable_literal)]",
    "",
    "/// Twiddles, in the order the reference's `ntt` and `intt` walk them.",
    f"pub const W: [u64; {len(polyr.RACC_W)}] = [",
    body + ",",
    "];",
    "",
    "/// `N^-1 mod Q`.",
    f"pub const N_INV: u64 = {polyr.RACC_NI};",
    "",
]
io.open(table, "w", encoding="utf-8", newline=NL).write(NL.join(header))
subprocess.run(["rustfmt", "--edition", "2024", table], check=True)
print("wrote", table)
