//! SPV against real state and real headers.
//!
//! The proofs here are generated by a real `StateDB` from a real applied block,
//! not hand-assembled. A test that built its own proof would be testing its own
//! arithmetic; what matters is that the *node's* prover and the *client's*
//! verifier agree, because they are the two halves that have to.
//!
//! Three properties are load-bearing:
//!
//! - **A proof must not verify against the wrong root.** Otherwise it proves
//!   nothing at all.
//! - **Fork choice must be on work, not length.** A thousand cheap headers must
//!   not outrank ten expensive ones, or a fake chain costs nothing.
//! - **A target below the network floor must be refused.** It is the single
//!   check that makes each header cost something.

#![allow(clippy::unwrap_used, clippy::expect_used)]

use custom_l1_node::core::{Block, BlockHeader, Transaction, TxOutput};
use custom_l1_node::crypto::dag::registry::{CacheRegistry, DagConfig};
use custom_l1_node::crypto::hybrid::{HybridSigningKey, generate_signing_key};
use custom_l1_node::crypto::pow::target_from_leading_zero_bits;
use custom_l1_node::state::{Account, Address, BlockContext, StateDB};
use maya_light_client::{HeaderChain, LightClient, LightClientError};
use tempfile::TempDir;

const HOLDERS: usize = 6;
const BALANCE: u64 = 1_000_000;

/// A chain that follows whatever it is handed.
///
/// Proof-of-work verification is off: mining a real header at a real target
/// would cost more than these tests are worth, and the checks being exercised
/// here — fork choice, the floor, and proof binding — are all reachable without
/// it. `a_header_below_the_difficulty_floor_is_refused` is the one that needs
/// the floor, and the floor is checked before the digest.
fn chain(genesis: BlockHeader) -> HeaderChain {
    // The easiest possible floor, so these tests can pick whatever difficulty
    // makes the fork-choice arithmetic legible. `DEFAULT_POW_LIMIT` is harder
    // than that and would refuse them — which is the floor doing its job, and is
    // what `a_header_below_the_difficulty_floor_is_refused` checks with a floor
    // of its own.
    let easiest = target_from_leading_zero_bits(0);
    HeaderChain::new(genesis, 0, easiest, CacheRegistry::new(DagConfig::NEVER))
        .without_pow_verification()
}

fn header(prev: [u8; 32], state_root: [u8; 32], zero_bits: u32) -> BlockHeader {
    BlockHeader {
        prev_hash: prev,
        state_root,
        timestamp: 1_756_252_800,
        nonce: 0,
        difficulty_target: target_from_leading_zero_bits(zero_bits),
        tx_root: [0; 32],
    }
}

/// A funded state database, and the keys that hold it.
fn funded() -> (StateDB, Vec<HybridSigningKey>, TempDir) {
    let dir = TempDir::new().expect("temp dir");
    let db = StateDB::open(dir.path()).expect("open");

    let holders: Vec<HybridSigningKey> = (0..HOLDERS)
        .map(|_| generate_signing_key().expect("key"))
        .collect();
    for holder in &holders {
        db.put_account(
            &holder.address(),
            &Account {
                balance: BALANCE,
                nonce: 0,
            },
        )
        .expect("fund");
    }
    (db, holders, dir)
}

// ---------------------------------------------------------------------------
// proofs against real state
// ---------------------------------------------------------------------------

#[test]
fn every_account_in_a_real_state_proves_against_its_root() {
    // Every account, not one: a Merkle path is a statement about a leaf's
    // position, and the interesting positions are the ones a person does not
    // pick by hand.
    let (db, holders, _dir) = funded();
    let root = db.state_root().expect("root");

    let client = LightClient::new(chain(header([0u8; 32], root, 0)));

    for holder in &holders {
        let proof = db
            .account_proof(&holder.address())
            .expect("read")
            .expect("account exists");
        assert!(client.verify_account(0, &proof).is_ok());
        assert_eq!(
            client.verified_balance(0, &proof).expect("balance"),
            BALANCE
        );
    }
}

#[test]
fn a_proof_does_not_verify_against_a_different_root() {
    // The property that makes a proof worth anything: bound to one state, not
    // to any state that happens to contain the account.
    let (db, holders, _dir) = funded();
    let proof = db
        .account_proof(&holders[0].address())
        .expect("read")
        .expect("exists");

    let client = LightClient::new(chain(header([0u8; 32], [0xAAu8; 32], 0)));
    assert!(matches!(
        client.verify_account(0, &proof).unwrap_err(),
        LightClientError::ProofMismatch { .. }
    ));
}

#[test]
fn a_proof_stops_verifying_once_the_account_it_names_moves() {
    // A balance that changed must not prove against the root it had before it
    // changed — the whole reason a light client can trust a stale proof is that
    // it cannot.
    let (db, holders, _dir) = funded();
    let old_root = db.state_root().expect("root");
    let stale = db
        .account_proof(&holders[0].address())
        .expect("read")
        .expect("exists");

    // Move some coin, which rewrites two accounts and therefore the root.
    let mut tx = Transaction::new(
        vec![],
        vec![TxOutput {
            amount: 1_000,
            recipient: holders[1].address(),
        }],
        0,
    );
    tx.sign(&holders[0]).expect("sign");
    let block = Block::new(header([0u8; 32], [0u8; 32], 0), vec![tx]);
    let new_root = db
        .apply_block(&block, BlockContext::at_height(1))
        .expect("apply");
    assert_ne!(new_root, old_root);

    // Against the old root it still verifies — it was true then, and a proof is
    // a statement about a moment.
    let old_client = LightClient::new(chain(header([0u8; 32], old_root, 0)));
    assert!(old_client.verify_account(0, &stale).is_ok());

    // Against the new one it does not.
    let new_client = LightClient::new(chain(header([0u8; 32], new_root, 0)));
    assert!(new_client.verify_account(0, &stale).is_err());

    // And a fresh proof does.
    let fresh = db
        .account_proof(&holders[0].address())
        .expect("read")
        .expect("exists");
    assert_eq!(
        new_client.verified_balance(0, &fresh).expect("balance"),
        BALANCE - 1_000
    );
}

#[test]
fn a_tampered_proof_is_refused() {
    let (db, holders, _dir) = funded();
    let root = db.state_root().expect("root");
    let client = LightClient::new(chain(header([0u8; 32], root, 0)));

    let honest = db
        .account_proof(&holders[0].address())
        .expect("read")
        .expect("exists");

    // Inflating the balance is the attack a light client exists to refuse.
    let mut inflated = honest.clone();
    inflated.account.balance = u64::MAX;
    assert!(client.verify_account(0, &inflated).is_err());

    // So is rewriting a sibling to fabricate a path.
    let mut forged = honest.clone();
    if let Some(step) = forged.path.first_mut() {
        step.sibling[0] ^= 1;
        assert!(client.verify_account(0, &forged).is_err());
    }

    // And so is claiming somebody else's balance under your own address.
    let mut impersonated = honest;
    impersonated.address = holders[1].address();
    assert!(client.verify_account(0, &impersonated).is_err());
}

#[test]
fn a_proof_survives_encoding() {
    // The client and the node are separate processes; a proof that did not
    // round-trip would work only in a test that never serialized it.
    use custom_l1_node::state::AccountProof;

    let (db, holders, _dir) = funded();
    let root = db.state_root().expect("root");
    let client = LightClient::new(chain(header([0u8; 32], root, 0)));

    let proof = db
        .account_proof(&holders[3].address())
        .expect("read")
        .expect("exists");
    let decoded = AccountProof::decode(&proof.encode()).expect("decode");

    assert_eq!(decoded, proof);
    assert!(client.verify_account(0, &decoded).is_ok());
}

#[test]
fn an_account_that_does_not_exist_has_no_proof() {
    // Absence is not provable here, and returning `None` says so rather than
    // handing back a proof of a zero balance that would look like evidence.
    let (db, _holders, _dir) = funded();
    let stranger: Address = [0x5Au8; 32];
    assert!(db.account_proof(&stranger).expect("read").is_none());
}

#[test]
fn a_proof_against_a_height_the_client_has_not_seen_is_refused() {
    // Verifying against a root nobody mined proves nothing, so the client
    // refuses rather than reaching for a root it does not hold.
    let (db, holders, _dir) = funded();
    let root = db.state_root().expect("root");
    let client = LightClient::new(chain(header([0u8; 32], root, 0)));

    let proof = db
        .account_proof(&holders[0].address())
        .expect("read")
        .expect("exists");

    assert!(matches!(
        client.verify_account(99, &proof).unwrap_err(),
        LightClientError::UnknownHeight(99)
    ));
}

#[test]
fn a_proof_from_a_chain_with_every_layer_populated_still_verifies() {
    // The layered fold is the part a naive SPV implementation gets wrong. With
    // trading, oracle, and governance records all present, an account path that
    // stopped at the accounts root would reach a value the header never
    // committed to.
    use custom_l1_node::core::TxKind;
    use custom_l1_node::core::dex_payload::AssetRegistration;
    use custom_l1_node::core::governance_payload::StakeLock;

    let (db, holders, _dir) = funded();

    let mut register = Transaction::with_kind(
        TxKind::RegisterAsset(AssetRegistration {
            symbol: *b"USD\0\0\0\0\0",
            total_supply: 1_000,
        }),
        0,
    );
    register.sign(&holders[0]).expect("sign");

    let mut lock = Transaction::with_kind(
        TxKind::LockStake(StakeLock {
            amount: 500,
            unlock_height: 10_000,
        }),
        0,
    );
    lock.sign(&holders[1]).expect("sign");

    let root = db
        .apply_block(
            &Block::new(header([0u8; 32], [0u8; 32], 0), vec![register, lock]),
            BlockContext::at_height(1),
        )
        .expect("apply");

    let client = LightClient::new(chain(header([0u8; 32], root, 0)));
    let proof = db
        .account_proof(&holders[2].address())
        .expect("read")
        .expect("exists");

    // Two layers folded above the accounts tree, and the proof carries both.
    assert!(proof.layers.len() >= 2, "layers were not folded in");
    assert!(client.verify_account(0, &proof).is_ok());
}

// ---------------------------------------------------------------------------
// header chain and fork choice
// ---------------------------------------------------------------------------

#[test]
fn a_header_with_an_unknown_parent_is_refused() {
    let mut chain = chain(header([0u8; 32], [1u8; 32], 0));
    assert!(matches!(
        chain
            .accept(header([0x99u8; 32], [2u8; 32], 0))
            .unwrap_err(),
        LightClientError::UnknownParent { .. }
    ));
}

#[test]
fn a_header_below_the_difficulty_floor_is_refused() {
    // Without this the whole construction is worthless: an attacker mines at a
    // target every digest satisfies and produces an arbitrarily long chain in
    // an instant.
    let genesis = header([0u8; 32], [1u8; 32], 8);
    let genesis_id = genesis.id();
    let mut chain = HeaderChain::new(
        genesis,
        0,
        target_from_leading_zero_bits(8),
        CacheRegistry::new(DagConfig::NEVER),
    )
    .without_pow_verification();

    // Easier than the floor: refused.
    assert!(matches!(
        chain.accept(header(genesis_id, [2u8; 32], 4)).unwrap_err(),
        LightClientError::TargetBelowFloor { .. }
    ));

    // At the floor: accepted.
    assert!(chain.accept(header(genesis_id, [2u8; 32], 8)).is_ok());
}

#[test]
fn fork_choice_follows_work_and_not_length() {
    // The property that makes a cheap chain lose. Ten hard headers must outrank
    // any number of easy ones.
    let genesis = header([0u8; 32], [1u8; 32], 1);
    let genesis_id = genesis.id();
    let mut chain = chain(genesis);

    // A long, cheap branch.
    let mut cursor = genesis_id;
    for index in 0..20u8 {
        let next = header(cursor, [index; 32], 1);
        cursor = next.id();
        chain.accept(next).expect("cheap header");
    }
    let cheap_tip = chain.tip().expect("tip").height;
    assert_eq!(cheap_tip, 20);

    // One expensive header off genesis. Twenty leading zero bits is 2^19 times
    // the work of one bit, so a single one outweighs the whole cheap branch.
    let expensive = header(genesis_id, [0xEEu8; 32], 20);
    let became_tip = chain.accept(expensive).expect("expensive header");

    assert!(
        became_tip,
        "one expensive header did not outrank twenty cheap"
    );
    assert_eq!(chain.tip().expect("tip").height, 1);
}

#[test]
fn a_losing_branch_is_kept_rather_than_discarded() {
    // A branch that loses today can win tomorrow, and a client that threw it
    // away would have to re-download it to follow the reorg.
    let genesis = header([0u8; 32], [1u8; 32], 4);
    let genesis_id = genesis.id();
    let mut chain = chain(genesis);

    let strong = header(genesis_id, [0xAAu8; 32], 12);
    let strong_id = strong.id();
    assert!(chain.accept(strong).expect("strong"));

    let weak = header(genesis_id, [0xBBu8; 32], 4);
    assert!(!chain.accept(weak).expect("weak"), "weak became the tip");

    assert_eq!(chain.len(), 3, "the losing branch was discarded");
    assert_eq!(chain.tip().expect("tip").header.id(), strong_id);
}

#[test]
fn a_reorg_rewrites_the_height_index() {
    // The subtle one. After a reorg the client must not answer a proof against
    // a header from the branch that lost — that is precisely the state in which
    // a stale proof verifies against a root nobody believes.
    let genesis = header([0u8; 32], [1u8; 32], 4);
    let genesis_id = genesis.id();
    let mut chain = chain(genesis);

    let losing = header(genesis_id, [0xBBu8; 32], 4);
    let losing_id = losing.id();
    chain.accept(losing).expect("losing");
    assert_eq!(chain.header_at(1).expect("height 1").header.id(), losing_id);

    let winning = header(genesis_id, [0xAAu8; 32], 16);
    let winning_id = winning.id();
    assert!(chain.accept(winning).expect("winning"));

    assert_eq!(
        chain.header_at(1).expect("height 1").header.id(),
        winning_id,
        "the height index still points at the abandoned branch"
    );
}

#[test]
fn a_proof_follows_the_reorg() {
    // End to end: two chains, two states, and a proof that is true on one and
    // false on the other.
    let (db, holders, _dir) = funded();
    let honest_root = db.state_root().expect("root");
    let proof = db
        .account_proof(&holders[0].address())
        .expect("read")
        .expect("exists");

    let genesis = header([0u8; 32], [1u8; 32], 4);
    let genesis_id = genesis.id();
    let mut chain = chain(genesis);

    // A weak branch committing to the honest root.
    chain
        .accept(header(genesis_id, honest_root, 4))
        .expect("honest");
    let client = LightClient::new(chain);
    assert!(client.verify_account(1, &proof).is_ok());

    // A stronger branch committing to something else. The proof stops
    // verifying, because the client now believes a different state.
    let mut chain = client.into_chain();
    assert!(
        chain
            .accept(header(genesis_id, [0xFFu8; 32], 16))
            .expect("attacker")
    );
    let client = LightClient::new(chain);
    assert!(matches!(
        client.verify_account(1, &proof).unwrap_err(),
        LightClientError::ProofMismatch { .. }
    ));
}
